[CCTRI-3968] Outdated "Cisco SecureX" identifier
CiscoSecurity/tr-05-docker-relay pull request #22
Opened 2023-08-10 15:33 UTC by Tempos

add Makefile, update Pipenv, normalize strings

2023-08-10 15:56 UTC, grzegorzbielecki requested changes

2023-08-10 15:56 UTC, grzegorzbielecki commented on README.md
> +- We need an application that will translate API requests from XDR Threat Response to the third-party integration, and vice versa.
I think Threat Response is also outdated - now this is just Cisco XDR

2023-08-14 11:26 UTC, grzegorzbielecki approved these changes

2023-08-16 08:51 UTC, opavlyshyn approved these changes

2023-08-16 08:56 UTC, jordan5rov approved these changes

2023-08-17 08:24 UTC, merged