Update Makefile and format files
CiscoSecurity/tr-05-docker-relay pull request #24
Opened 2023-09-04 16:03 UTC by grzegorzbielecki

2023-09-13 14:39 UTC, Tempos approved these changes

2023-09-28 10:55 UTC, jordan5rov requested changes

2023-09-28 10:55 UTC, jordan5rov commented on code/Pipfile
>  [dev-packages]
we need to think about adding the 'pip-audit' library here for the dependencies investigations

2023-09-28 10:58 UTC, grzegorzbielecki commented on code/Pipfile
>  [dev-packages]
I will check it on a new branch

2023-09-28 11:03 UTC, grzegorzbielecki commented on code/Pipfile
> +python_version = "3.11"
Done

2023-09-28 14:14 UTC, grzegorzbielecki commented on code/Pipfile
>  [dev-packages]
Done

2023-09-28 14:18 UTC, jordan5rov approved these changes

2023-09-28 14:23 UTC, merged